build_test_and_package_app:
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  cache:
    paths:
      - .m2/repository/
      - target/
  image: maven:3.8.5-openjdk-17
  script:
    - mvn $MAVEN_CLI_OPTS install

build_docker_image:
  needs:
  - build_test_and_package_app
  image: docker:20.10.17-cli
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - make build_app
