variables:
  APP_NAME: todo-backend-quarkusapp
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

build_test_and_package_app:
  image: maven:3.8.5-openjdk-17
  artifacts:
    untracked: true
    paths:
      - target
    expire_in: 1 days
  before_script:
    - curl https://github.com/aquasecurity/trivy/releases/download/v0.30.4/trivy_0.30.4_Linux-64bit.tar.gz --output trivy.tar.gz
    - ls -la
    - echo ${CI_COMMIT_BRANCH}
  script:
    - mvn clean install

build_docker_image:
  needs:
  - build_test_and_package_app
  image: docker:20.10.17-cli
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - curl https://github.com/aquasecurity/trivy/releases/download/v0.30.4/trivy_0.30.4_Linux-64bit.tar.gz --output trivy.tar.gz
    - ls -la
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
  script:
    - docker build -f src/main/docker/Dockerfile.jvm -t ${APP_NAME} .
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:${CI_COMMIT_BRANCH}
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:latest
