build_test_and_package_app:
  image: azul/zulu-openjdk:17
  before_script:
  - apt update -y && apt install make -y
  script:
    - make package_app


build_docker_image:
  image: docker:20.10.17-cli
  before_script:
    - apt update -y && apt install make -y
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - make build_app
