variables:
  APP_NAME: todo-backend-quarkusapp

build_test_and_package_app:
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean install

build_docker_image:
  needs:
  - build_test_and_package_app
  image: docker:20.10.17-cli
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $REGISTRY_USER
    - echo $REGISTRY_TOKEN
    - docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN
  script:
    - echo $REGISTRY_USER
    - echo $APP_NAME
    - docker build -f src/main/docker/Dockerfile.jvm -t mombe090/$APP_NAME .
