variables:
  APP_NAME: todo-backend-quarkusapp
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:20.10.17-dind

cache:
  paths:
    - .m2/repository

build_test_and_package_app:
  image: maven:3.8.5-openjdk-17
  artifacts:
    untracked: true
    paths:
      - target
    expire_in: 1 days
  before_script:
    - echo ${CI_COMMIT_BRANCH}
  script:
    - mvn clean install

include:
  # Trivy integration with GitLab Container Scanning
  - remote: "https://github.com/aquasecurity/trivy/raw/main/contrib/Trivy.gitlab-ci.yml"

build_docker_image:
  needs:
  - build_test_and_package_app
  dependencies:
    - build_test_and_package_app
  image: docker:20.10.17-cli

  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
  script:
    - docker build -f src/main/docker/Dockerfile.jvm -t ${APP_NAME} .
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:${CI_COMMIT_BRANCH}
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:latest
