variables:
  APP_NAME: todo-backend-quarkusapp
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

build_test_and_package_app:
  image: maven:3.8.5-openjdk-17
  artifacts:
    untracked: true
    paths:
      - target
    expire_in: 1 days
  before_script:
    - echo ${CI_COMMIT_BRANCH}
  script:
    - mvn clean install

build_docker_image:
  needs:
  - build_test_and_package_app
  image: docker:20.10.17-cli
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk update && apk --no-cache add curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.17.0
  script:
    - docker build -f src/main/docker/Dockerfile.jvm -t ${APP_NAME} .
    - trivy image ${APP_NAME}
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_TOKEN}
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:${CI_COMMIT_BRANCH}
    - docker tag ${APP_NAME} ${REGISTRY_USER}/${APP_NAME}:latest
    - docker push ${REGISTRY_USER}/${APP_NAME}:${CI_COMMIT_BRANCH}
    - docker push ${REGISTRY_USER}/${APP_NAME}:latest