apiVersion: v1
kind: Namespace
metadata:
  name: todos

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-backend
  name: todo-backend
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - image: mombe090/todo-backend-quarkusapp:todo-init
        name: todo-backend-quarkusapp

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-backend
  name: todo-backend
  namespace: todos
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-backend
  type: NodePort

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: todo-backend
  namespace: todos
spec:
  ingressClassName: nginx
  rules:
  - host: todoapp.backend.local
    http:
      paths:
      - backend:
          service:
            name: todo-backend
            port:
              number: 8080
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
