apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todos-kustomize-dev
namePrefix: dev-

bases:
  - ../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
